#!/bin/bash

uppercase_distro=$(grep ^NAME= /etc/os-release | cut -d= -f2 | tr -d '"' | tr -d ' ')
if [[ -n $SNAP_USER_COMMON ]]; then
    uppercase_distro=$(grep ^NAME= /var/lib/snapd/hostfs/etc/os-release | cut -d= -f2 | tr -d '"' | tr -d ' ')
fi
distribution=$(echo "$uppercase_distro" | tr '[:upper:]' '[:lower:]')

check_special_names() {
    if [[ "$distribution" == "arch" ]]; then
        distribution="archlinux"
    elif [[ "$distribution" == "opensuseleap" ]]; then
        distribution="opensuse"
    elif [[ "$distribution" == "ubuntucore" ]]; then
        distribution="ubuntu"
    fi
}

download_snap() {
    curl -L -o "${SNAP_USER_COMMON}/update-$distribution" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/os/update-$distribution.py"
    curl -L -o "${SNAP_USER_COMMON}/version_mapping.py" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/os/version_mapping.py"
    chmod +x "${SNAP_USER_COMMON}/update-$distribution"
}
download_nosnap() {
    mkdir "/home/$USER/linux-os-updater"
    curl -L -o "/home/$USER/linux-os-updater/update-$distribution" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/os/update-$distribution.py"
    curl -L -o "/home/$USER/linux-os-updater/version_mapping.py" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/os/version_mapping.py"
    chmod +x "/home/$USER/linux-os-updater/update-$distribution"
}

echo "Welcome to Linux OS Updater!"
sleep 2

echo "Setting up files..."

echo "copying update files..."

check_special_names
if command -v snap &> /dev/null && [[ -n "$SNAP" ]]; then
    download_snap
else
    download_nosnap
fi

declare -A names=(
    ["manjaro"]="archlinux"
    ["opensuseleap"]="opensuse"
)

for key in "${!names[@]}"; do
    
    if [[ "$distribution" == "${names[$key]}" ]]; then
        mv "/home/$USER/opt/linux-os-updater/update-$distribution.py" "/home/$USER/opt/linux-os-updater/update-$key.py"
        break
    fi
done

echo -e "\n\n\n\n"

echo -e "\033[0;32mScript successfully updated! Restart the terminal for changes to take effect.\033[0m"
