#!/bin/sh

distro=$(grep ^ID= /etc/os-release | cut -d= -f2 | tr -d '"')
if [ "$distro" = "manjaro" ]; then
  distro="archlinux"
fi

echo "copying update files..."
sudo wget -O "/usr/bin/update-$distro" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/os/update-$distro.py"
sudo wget -O "/usr/bin/version_mapping" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/os/version_mapping.py"
sudo wget -O "/usr/bin/update-os-updater" "https://raw.githubusercontent.com/CrypticVerse/linux-os-updater/refs/heads/master/tools/update-os-updater"
sudo chmod +x "/usr/bin/update-$distro" && sudo chmod +x "/usr/bin/update-os-updater"

echo -e "\033[0;32mScript successfully updated! Restart the terminal for changes to take effect.\033[0m"