name: linux-os-updater
version: git
summary: 'A tool for updating and managing Linux operating system packages and versions'
description: |
  A comprehensive tool designed to update and manage packages and versions of the Linux operating system efficiently.

base: core24
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  linux-os-updater:
    command: bin/linux-os-updater
    plugs:
      - network
      - home
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.8/site-packages

parts:
  linux-os-updater:
    plugin: python
    source: .
    stage-packages:
      - curl
      - python3
      - python3-pip
    override-build: |
      chmod +x linux-os-updater
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp linux-os-updater $SNAPCRAFT_PART_INSTALL/bin/linux-os-updater
